### ISSUE TITLE
error in statistics API, access to nil class

### ISSUE THREAD

**Issue by jwoschitz** [sozialhelden/brokenlift#2]
API call:
http://brokenlifts.org/api/lifts/140/statistics.json/?days=200

Error message:
`You have a nil object when you didn't expect it!`
`You might have expected an instance of Array.`
`The error occurred while evaluating nil.[]=`

Stacktrace:
`app/models/lift.rb:121:in `block (2 levels) in get_statistics'`
`app/models/lift.rb:115:in `each'`
`app/models/lift.rb:115:in `block in get_statistics'`
`app/models/lift.rb:93:in `each'`
`app/models/lift.rb:93:in `get_statistics'`
`app/controllers/api/lifts_controller.rb:34:in `statistics'`

**Comment by wikimatze** [comment]
This is fixed by now.

**Comment by jwoschitz** [comment]
same error occurs for http://brokenlifts.org/api/lifts/3/statistics.json/?days=200

```
NoMethodError (undefined method `[]=' for nil:NilClass):
  app/models/lift.rb:121:in `get_statistics'
  app/models/lift.rb:115:in `each'
  app/models/lift.rb:115:in `get_statistics'
  app/models/lift.rb:93:in `each'
  app/models/lift.rb:93:in `get_statistics'
  app/controllers/api/lifts_controller.rb:34:in `statistics'
```
